### ISSUE TITLE
Config unit-test

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/uno-react#5] opened 2019-02-06 22:17 UTC
- [ ] Config unit test

**Comment by AnyxLeo** [comment] 2019-02-12 15:20
The hooks cannot be tested by now, the enzyme doesn't support hooks yet.

**Comment by geoperez** [comment] 2019-02-12 16:51
Continue with other files.

**Comment by Ferleomos** [comment] 2019-02-19 19:07
Some tests have been added. The issue is going to be closed in order to check what files are able to be tested.

**Closed by Ferleomos** 2019-02-19 19:07 UTC
Labels: enhancement
